### ISSUE TITLE
Préparation de l'environnement GitHub

### ISSUE THREAD

**Issue by SiwarZaghmi** [SiwarZaghmi/GitHub_Analytics#2]
Dans cette étape on va :

- [x] créer le Repository 

- [x] Créer le projet 

- [x] Modifier la Template en "Automated Kanban "

- [x] Ajouter les collaborateurs
